@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
Person(техник, "Техник", "Мониторинг камер")
Person(зоотехник, "Зоотехник", "Уход за животными")
Person(оператор, "Оператор", "Управление фермой")
Person(администратор, "Администратор", "Управление фермами")

System_Boundary(platform, "АгроПром Х - Цифровая ферма") {
    Container(house, "Данные с загонов")

    Container(мобильное_приложение, "Мобильное приложение", "", "Полевые работы")
    Container(веб_портал, "Веб-портал", "", "Управление хозяйством")

    Container(agent, "Агент", "Размещается на ферме", "Хранение данных фермы, Доступ к данным, Аутентификация, Мониторинг, Управление")
}

Container(master, "Центральный сервер", "", "Хранение данных ферм, Агрегация данных, Доступ к данным")

Container(аналитика, "Аналитика")

' Персонал
Rel(техник, мобильное_приложение, "Использует")
Rel(зоотехник, мобильное_приложение, "Использует")

Rel(оператор, веб_портал, "Использует")
Rel(администратор, master, "Использует")

' Сбор данных
Rel(house, agent, "Передает данные", "")

' Пользовательский функционал
Rel(мобильное_приложение, agent, "Использует")
Rel(веб_портал, agent, "Использует")

Rel_Up(master, agent, "Использует")

' Внешние интеграции
Rel(master, аналитика, "Предоставляет метрики")

@enduml