@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===
Person(техник, "Техник", "Мониторинг камер")
Person(зоотехник, "Зоотехник", "Уход за животными")
Person(оператор, "Оператор", "Управление фермой")
Person(администратор, "Администратор", "Управление фермами")

System_Boundary(farm, "АгроПром Х - Цифровая ферма") {
    Container(house, "Данные с загонов", "Камеры, датчики")

    Container(мобильное_приложение, "Мобильное приложение", "", "Полевые работы, получение оповещений")
    Container(веб_приложение, "Веб-приложение", "", "Управление хозяйством, общий мониторинг")

    Container(agent, "Агент", "Размещается на ферме", "Хранение данных фермы, Доступ к данным, Аутентификация, Мониторинг, Управление")
}

System_Boundary(office, "АгроПром Х - Управление") {
    Container(master, "Центральный сервер", "", "Агрегация данных, Доступ к данным, Доступ к агенту")
    ContainerDb(master_db, "Центральная БД", "", "Хранение данных о всех фермах")

    Container(веб_портал, "Веб-портал", "", "Управление всеми фермами")

    Container(аналитика, "Аналитика", "ERP", "Построение метрик, анализ")
}

' Персонал
Rel(техник, мобильное_приложение, "Использует")
Rel(зоотехник, мобильное_приложение, "Использует")

Rel(оператор, веб_приложение, "Использует")
Rel(администратор, веб_портал, "Использует")

' Сбор данных
Rel(house, agent, "Передает данные", "")

' Пользовательский функционал
Rel(мобильное_приложение, agent, "Использует")
Rel(веб_приложение, agent, "Использует")

Rel_Up(master, agent, "Использует")

Rel(веб_портал, master, "Использует")

' Внешние интеграции
Rel(master, аналитика, "Предоставляет метрики")

@enduml