@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===

Person(техник, "Техник", "Мониторинг камер")
Person(зоотехник, "Зоотехник", "Уход за животными")
Person(оператор, "Оператор", "Управление фермой")
Person(администратор, "Администратор", "Управление фермами")


System_Boundary(farm, "АгроПром Х - Цифровая ферма") {
    Container(house, "Данные с загонов", "Камеры, RFID-метки, датчики")

    Container(iot_gateway, "IoT-Шлюз", "ИИ", "Читает данные с устройств, распознает видео, унифицирует данные")

    Container(мобильное_приложение, "Мобильное приложение", "", "Полевые работы, получение оповещений")
    Container(веб_приложение, "Веб-приложение", "", "Управление хозяйством, общий мониторинг")

    Container(agent, "Агент", "Размещается на ферме", "Доступ к данным, Аутентификация, Мониторинг, Управление")

    ContainerDb(agent_db, "Локальная БД", "Размещается на ферме", "Хранение данных о ферме")
}

System_Boundary(office, "АгроПром Х - Управление") {
    Container(master, "Центральный сервер", "", "Агрегация данных, Доступ к данным")
    ContainerDb(master_db, "Центральная БД", "", "Хранение данных о всех фермах")

    Container(веб_портал, "Веб-портал", "", "Управление всеми фермами")

    Container_Ext(аналитика, "Аналитика", "ERP", "Построение метрик, анализ")
}

' Персонал
Rel(техник, мобильное_приложение, "Использует")
Rel(зоотехник, мобильное_приложение, "Использует")

Rel(оператор, веб_приложение, "Использует")
Rel(администратор, веб_портал, "Использует")

' Сбор данных
Rel_Down(house, iot_gateway, "Передает данные", "")
Rel_Down(iot_gateway, agent, "Преобразует данные")

' Агент
Rel_L(agent, agent_db, "Использует")

' Пользовательский функционал
Rel(мобильное_приложение, agent, "Использует")
Rel(веб_приложение, agent, "Использует")

' Центральный сервер
BiRel_Down(agent, master, "Синхронизируется")
Rel_L(master, master_db, "Использует")

Rel(веб_портал, master, "Использует")

' Внешние интеграции
Rel_R(master, аналитика, "Предоставляет метрики")

@enduml