@startuml Архитектура_АгроТех_Системы_v4

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

' === Участники ===

Person(техник, "Техник", "Мониторинг камер")
Person(зоотехник, "Зоотехник", "Уход за животными")
Person(оператор, "Оператор", "Управление фермой")
Person(администратор, "Администратор", "Управление фермами")


System_Boundary(platform, "АгроПром Х - Цифровая ферма") {
    Container(house, "Данные с загонов", "Камеры, RFID-метки")

    Container(iot_platform, "IoT платформа")

    Container(мобильное_приложение, "Мобильное приложение", "", "Полевые работы")
    Container(веб_портал, "Веб-портал", "", "Управление хозяйством")

    Container(agent, "Агент", "Размещается на ферме", "Доступ к данным, Аутентификация, Мониторинг, Управление")

    ContainerDb(agent_db, "Локальная БД", "Размещается на ферме", "Хранение данных о ферме")
}

Container(master, "Центральный сервер", "", "Агрегация данных, Доступ к данным")
ContainerDb(master_db, "Центральная БД", "", "Хранение данных о всех фермах")

Container(аналитика, "Аналитика")

' Персонал
Rel(техник, мобильное_приложение, "Использует")
Rel(зоотехник, мобильное_приложение, "Использует")

Rel(оператор, веб_портал, "Использует")
Rel(администратор, master, "Использует")

' Сбор данных
Rel_Down(house, iot_platform, "Передает данные", "")
Rel_Down(iot_platform, agent, "Преобразует данные")

' Агент
Rel_L(agent, agent_db, "Использует")

' Пользовательский функционал
Rel(мобильное_приложение, agent, "Использует")
Rel(веб_портал, agent, "Использует")

' Центральный сервер
BiRel_Down(agent, master, "Синхронизируется")
Rel_L(master, master_db, "Использует")

' Внешние интеграции
Rel_R(master, аналитика, "Предоставляет метрики")

@enduml