@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

ContainerDb_Ext(agent_db, "Локальная БД", "", "Хранение данных о ферме")
ContainerQueue_Ext(agent_service_bus, "Шина данных", "")

Container_Boundary(agent_control, "Сервис управления") {
    Component(DataLayer, "DataLayer", "", "Обеспечивает доступ к данным")

    Component(TasksListener, "TasksListener", "", "Слушает очередь сообщений на новые задачи")

    Component(TasksController, "TasksController", "", "Выполнение индивидуальными задачами управления")

    Component(EventPublisher, "EventPublisher", "", "Публикует результирующие события в шину данных")
}

Rel(DataLayer, agent_db, "Использует")
Rel(agent_service_bus, TasksListener, "Слушает")
Rel(TasksListener, TasksController, "Использует")

Rel(TasksController, DataLayer, "Использует")

Rel(TasksController, EventPublisher, "Использует")

Rel(EventPublisher, agent_service_bus, "Публикует", "события")

@enduml