@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

ContainerDb_Ext(master_db, "Центральная БД", "")
ContainerQueue_Ext(master_service_bus, "Шина данных", "")

Container_Boundary(agent_monitoring, "Сервис мониторинга") {
    Component(DataLayer, "DataLayer", "", "Слой доступа к данным")

    Component(EventsReader, "EventsReader", "", "Читает и слушает необходимый поток данных из очереди")
    
    Component(DetectorController, "DetectorController", "", "Выявляет аномальные события")

    Component(EventPublisher, "EventPublisher", "", "Публикует события")
}

Rel(DataLayer, master_db, "Использует")
Rel(master_service_bus, EventsReader, "Читает метрики")

Rel(DetectorController, DataLayer, "Использует")
Rel(DetectorController, EventsReader, "Использует")
Rel(DetectorController, EventPublisher, "Использует")

Rel(EventPublisher, master_service_bus, "Публикует")

@enduml